# fly.toml file generated for twilight-snow-8806 on 2023-01-08T20:54:28+08:00

app = "twilight-snow-8806"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8081"
HOST = "https://twilight-snow-8806.fly.dev"
APP_SLUG = "railway-test-app-cli3"
SHOPIFY_API_KEY = "fa48aa1af0a56f52208efea6bd49e4b1"
SCOPES = "write_products"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
